version: '3.8'

services:
  # Сервис для PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bd_rent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сервис для приложения
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/bd_rent?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      sh -c "
        npm install &&
        npx prisma migrate dev --name init &&
        npx prisma migrate deploy && 
        npm run dev
      "

volumes:
  postgres_data:
